spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auction_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8088
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html